version: '3'

services:
  web:
    build: .
    volumes:
      - /tmp/log/supervisord/:/var/log/supervisord/
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    environment:
      - OPENCGA_CONF=/etc/htsget_server/opencga.json
      - VCF_TYPES=/etc/vcf_types.tsv
  nginx:
    image: nginx:1.15.1
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /tmp/log/nginx/:/var/log/nginx/
    depends_on:
      - web